---
## seedbox
version: "3"
services:
## Gluetun
    # https://hub.docker.com/r/qmcgaw/gluetun
    # https://github.com/qdm12/gluetun/wiki/Environment-variables
    # https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun
    # https://github.com/qdm12/gluetun/wiki/Private-internet-access
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # network_mode: host
    # network_mode: bridge
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - /appdata/gluetun:/gluetun
    environment:
      - TZ=##USE##YOUR#OWN##
      - VPN_TYPE=##USE##YOUR#OWN##
      - VPNSP=##USE##YOUR#OWN##
      - REGION=##USE##YOUR#OWN##
      - OPENVPN_USER=##USE##YOUR#OWN##
      - OPENVPN_PASSWORD=##USE##YOUR#OWN##
    ports:
      - 6881:6881/tcp # QBittorrent
      - 6881:6881/udp # QBittorrent
      - 8080:8080
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    restart: unless-stopped
## Q Bittorrent
  # https://hub.docker.com/r/linuxserver/qbittorrent
  # DEFAULT PASSWORD IS admin/adminadmin
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    privileged: true
    network_mode: "container:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=##USE##YOUR#OWN##
      - WEBUI_PORT=8080
    volumes:
      - /appdata/qbittorrent:/config
      - /media/##USE##YOUR#OWN##/Torrents:/downloads
      - /media/##USE##YOUR#OWN##/Media:/media
    restart: unless-stopped
## Jackett
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=##USE##YOUR#OWN##
      - AUTO_UPDATE=true
    volumes:
      - /appdata/jackett:/config
      - /media/##USE##YOUR#OWN##/Torrents:/downloads
      - /media/##USE##YOUR#OWN##/Media:/media
    ports:
      - 9117:9117
    restart: unless-stopped
