---
services:
    # https://hub.docker.com/r/qmcgaw/gluetun
    # https://github.com/qdm12/gluetun/wiki/Environment-variables
    # https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun
    # https://github.com/qdm12/gluetun/wiki/Private-internet-access
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # network_mode: host
    # network_mode: bridge
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /appdata/gluetun:/gluetun
    env_file:
      - .env
    environment:
      - TZ=America/Los_Angeles
      #- #VPN_TYPE=##USE##YOUR#OWN##
      #- #VPNSP=##USE##YOUR#OWN##
      #- #REGION=##USE##YOUR#OWN##
      #- #OPENVPN_USER=##USE##YOUR#OWN##
      #- #OPENVPN_PASSWORD=##USE##YOUR#OWN##
      - VPN_SERVICE_PROVIDER=privado
      - SERVER_COUNTRIES=United States
    ports:
      - 6881:6881/tcp # QBittorrent
      - 6881:6881/udp # QBittorrent
      - 8080:8080
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    restart: unless-stopped
## Q Bittorrent
  # https://hub.docker.com/r/linuxserver/qbittorrent
  # DEFAULT PASSWORD IS admin/adminadmin
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    privileged: true
    network_mode: "container:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - WEBUI_PORT=8080
    volumes:
      - /appdata/qbittorrent:/config
      - /media/Media/Torrents:/downloads
      - /media/Media:/media
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - AUTO_UPDATE=true
    volumes:
      - /appdata/jackett:/config
      - /media/Media/Torrents:/downloads
      - /media/Media:/media
    ports:
      - 9117:9117
    restart: unless-stopped
