---

- name: Create Directories for media
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: '1000'
  loop: "{{ pvr_directories }}"

- name: Create Directories for appdata
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: '1000'
  loop: "{{ appdata_directories }}"
